accesio:
  version: VERSION
  css:
    base:
      dist/vendor/css/min/remixicon.min.css: { minified: true }
      dist/css/global/base.css: { }
      dist/css/global/typography.css: { }
      dist/css/global/buttons-links.css: { }
      dist/css/global/media.css: { }
      dist/css/global/list.css: { }
      dist/css/global/tables.css: { }
  js:
    dist/js/once.js: { minified: true, defer: true, async: true }
    dist/js/min/mmenu.min.js: { minified: true, defer: true, async: true }
    dist/js/accesio.js: { }
  dependencies:
    - core/jquery
    - core/drupal
    - core/jquery.once
    - core/drupal.dialog.ajax

header:
  css:
    base:
      dist/css/header/header.css: { }
      dist/css/header/branding.css: { }

footer:
  css:
    base:
      dist/css/footer/footer.css: { }

layout:
  css:
    base:
      dist/css/layout/grid.css: { }
      dist/css/layout/grid-addons.css: { }

menu_widescreen:
  css:
    base:
      dist/css/navigation/menu-widescreen.css: { }
  js:
    dist/js/jquery-meganav.js: { defer: true, async: true }

menu_utility:
  css:
    base:
      dist/css/navigation/menu-utility.css: { }

pager:
  css:
    base:
      dist/css/navigation/pager.css: { }

blog_post:
  css:
    theme:
      dist/css/content/blog-post.css: { }

author:
  css:
    theme:
      dist/css/content/author.css: { }

blog_hero:
  css:
    theme:
      dist/css/components/blog-hero.css: { }

hero:
  css:
    theme:
      dist/css/components/hero.css: { }

c_text:
  css:
    theme:
      dist/css/components/c-text.css: { }

text_bg:
  css:
    theme:
      dist/css/components/text-bg.css: { }

timeline_media:
  css:
    theme:
      dist/css/components/timeline-media.css: { }

timeline_simple:
  css:
    theme:
      dist/css/components/timeline-simple.css: { }

stats:
  css:
    theme:
      dist/css/components/stats.css: { }

quote:
  css:
    theme:
      dist/css/components/quote.css: { }

view_md_icons:
  css:
    theme:
      dist/css/views/view-md-icons.css: { }

views:
  css:
    theme:
      dist/css/views/views.css: { }

share:
  css:
    theme:
      dist/css/elements/share.css: { }

form:
  js:
    dist/js/form.js: { defer: true, async: true }
  css:
    theme:
      dist/css/elements/form.css: { }

page_title:
  css:
    theme:
      dist/css/elements/page-title.css: { }

accordion:
  css:
    theme:
      dist/css/components/accordion.css: { }
  js:
    dist/js/van11y-accessible-accordion-aria.js: { defer: true, async: true }

accesio_youtube_bg:
  js:
    dist/js/jquery.mb.YTPlayer.js: { defer: true, async: true }

accesio_vimeo_bg:
  js:
    dist/js/jquery.mb.vimeo_player.js: { defer: true, async: true }

masonry:
  js:
    dist/js/imagesloaded.pkgd.js: { }
    dist/js/isotope.pkgd.js: { }

a11y_tabs:
  css:
    theme:
      dist/css/components/tabs.css: { }
  js:
    dist/js/van11y-accessible-tab-panel-aria.js: { defer: true, async: true }

admin:
  css:
    theme:
      dist/css/utility/admin-tabs.css: { }

messages:
  css:
    theme:
      dist/css/utility/messages.css: { }

layout_builder_ui:
  css:
    theme:
      dist/css/utility/layout-builder-ui.css: { }

layout_bricks:
  css:
    theme:
      dist/css/layout/two-column-bricks.css: { }

stats_lb:
  css:
    theme:
      dist/css/components/stats-lb.css: { }

hero_lb:
  css:
    theme:
      dist/css/components/hero-lb.css: { }
