name: accesio
recipe: drupal9
config:
  php: '8.1'
  composer_version: 2
  via: 'apache:2.4'
  webroot: web
  database: 'mysql:5.7'
  drush: true
  xdebug: true
  config:
    php: lando/config/php.ini
services:
  node:
    type: 'node:18'
    scanner: false
    ssl: true
    sslExpose: false
    globals:
      gulp-cli: latest
    overrides:
      ports:
        - '32941:32941'
    command: tail -f /dev/null && cd /app/web/themes/custom/accesio && npm install
  appserver:
    xdebug: true
    run:
      - composer self-update
    config:
      php: lando/config/php.ini
    type: 'php:8.1'
    overrides:
      environment:
        PHP_IDE_CONFIG: serverName=appserver
        DRUSH_OPTIONS_URI: 'http://accesio.lndo.site'
tooling:
  node:
    service: node
  npm:
    service: node
  npx:
    service: node
  gulp:
    service: node
