<?php

/**
 * @file
 * Contains accesio_styles.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function accesio_styles_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the accesio_styles module.
    case 'help.page.accesio_styles':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Generates a page with all the pattern library styles') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function accesio_styles_theme() {
  return [
    'accesio_styles' => [
      'render element' => 'children',
    ],
    'atoms_colors' => [
      'render element' => 'children',
    ],
    'atoms_layout' => [
      'render element' => 'children',
    ],
    'atoms_typography' => [
      'render element' => 'children',
    ],
    'atoms_links' => [
      'render element' => 'children',
    ],
    'atoms_forms' => [
      'render element' => 'children',
    ],
    'atoms_feedback' => [
      'render element' => 'children',
    ],
    'atoms_images' => [
      'render element' => 'children',
    ],
    'atoms_quotes' => [
      'render element' => 'children',
    ],
  ];
}
