#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall theme
##
## Usage: fin theme

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
THEME_DIR="${DOCROOT_PATH}/${THEME}"

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------
#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

## CD into the theme folder.
cd web/themes/custom/accesio

# Remove the 'node_modules' folder for good measure before we install.
if [ -d "$node_modules" ]; then
echo -e "${yellow}Removing node_modules folder${NC}"
rm -R node_modules
fi

# Source / reload profiles for good measure.
echo -e "${green}Reloading Profiles${NC}"
source ~/.bashrc
source ~/.nvm/nvm.sh

# Install Node 10.16.3
nvm install 10.16.3

# set the global version of node being used.
echo -e "${green}Set the default version of node and use it${NC}"
nvm alias default 10.16.3
nvm use

echo -e "${green}NPM installing gulp CLI${NC}"
npm install --global gulp-cli

echo -e "${green}NPM installing node modules${NC}"
npm install

#-------------------------- END: Execution --------------------------------
